name: CI Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to private registry
        uses: docker/login-action@v3
        with:
          registry: harbor.chunha.ddns.net:9443
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .              # Look at the whole repo
          file: ./app/Dockerfile      # Use the Dockerfile in the root
          push: true
          #tags: harbor.chunha.ddns.net:9443/${{ github.repository }}/demo-app:latest
          tags: harbor.chunha.ddns.net:9443/private/demo-app:latest